#!/bin/bash
set -e

wget -qO- https://github.com/ElementsProject/elements/archive/elements-0.18.1.9.tar.gz | tar -xvz -C /tmp
cd /tmp/elements-elements-0.18.1.9/depends
make NO_QT=1 NO_UPNP=1
cd ..
./autogen.sh
./configure --without-gui --with-incompatible-bdb
make
make install
